### ISSUE TITLE
Is there a version of pure Vue?

### ISSUE THREAD

**Issue by Alvazz** [ctf0/Laravel-Media-Manager#102]
> What version of Laravel are you using? (nothing lower than v5.4).

5.7

> is it an issue related to installation or usage ?

usage

> what is the error you are getting ?

No

> Extra Info "attaching a screen shot would be very helpful"

...

> Do You Know A Solution For this Issue ?

**Comment by ctf0** [comment]
what do u mean? the js in the package is either vue or vanilla js

**Comment by Alvazz** [comment]
I mean, can use it without the combination of laravel? Just used in vuejs, but I think it shouldn't, because I found that the project package relies on a lot of laravel stuff, including filesystem

**Comment by Alvazz** [comment]
@ctf0 can u try integration your package whit this project?

[https://github.com/inertiajs/inertia-vue](url)

i try a lot of times, and more than 7 ways. look like cant integration them together

**Comment by ctf0** [comment]
> I mean, can use it without the combination of laravel? Just used in vuejs, but I think it shouldn't, because I found that the project package relies on a lot of laravel stuff, including filesystem

because this is a file manager which needs a way to communicate with the file system layer, the other option for not using laravel is going with another server language ex`node, go, etc...` which am not familiar with any

https://github.com/ctf0/Laravel-Media-Manager/issues/11

> https://github.com/inertiajs/inertia-vue

am aware of inertia but i havent played with it yet, however the package already use a caching layer to make navigation quicker so am not sure how inertia will fit or what extra does it offer

**Comment by Alvazz** [comment]
yes, you are right.
