### ISSUE TITLE
Cannot publish vendor

### ISSUE THREAD

**Issue by vhchung** [ctf0/Laravel-Media-Manager#14]
I use Laravel 5.5. I still need to add the service provider to `config/app.php` to make `php artisan vendor:publish ..` works. But next I got this error
```
[ErrorException]                                          
  array_push() expects parameter 1 to be array, null given 
```

**Comment by vhchung** [comment]
I fixed this issue. Edit `composer.json` and add this line to the end of `scripts` block
```
"post-autoload-dump": []
```

**Comment by ctf0** [comment]
hi @vhchung this issue is related to https://github.com/ctf0/PackageChangeLog/blob/1a8a3ee6af90b677e3e3bbca2954770713ff70a6/src/PackageChangeLogServiceProvider.php#L56 which all it does is read your `composer.json` `scripts.post-autoload-dump` array

also any command should work as usual without the need to manually register the SP, this is kinda weird that u need to do that.

**Comment by vhchung** [comment]
My bad. I have installed wrong version of Laravel. Thank you for your support.

**Comment by ctf0** [comment]
@vhchung can u tell me what was the laravel version you got the error with ?

**Comment by vhchung** [comment]
I use Laravel 5.5

**Comment by vhchung** [comment]
I got the error with Laravel 5.4
