### ISSUE TITLE
[Question] Bulk Upload

### ISSUE THREAD

**Issue by blisstechllc** [ctf0/Laravel-Media-Manager#145]
I love this package so far and I was looking for an option to upload from an imported folder. Like a scheduled task in the laravel scheduler that scans a folder for newly uploaded images. I am looking to possibly use this on a home media server with 200 + GB's of media so dragging and dropping that into dropzone might cause all kinds of issues? Plus that would be great to just backup images from a phone to folder on the media server and have this automatically import those into media library once a day.

**Comment by ctf0** [comment]
> the tickets have a template, plz use it.

as for ur question, the manager for the most part copy files 
- from a point A ex.ur desktop
- to point B ex.ur server

and display them.

so if i understand ur question, in ur case if for example the fs disk u r using is `public`
```php
'public' => [
    'driver'     => 'local',
    'root'       => storage_path('app/public'),
    'url'        => env('APP_URL') . '/storage',
    'visibility' => 'public',
],
```

it means that the manager will display any file/folder under the path `storage/public`.
so instead of using the upload process, we can instead move/save the files directly to that folder and next time u open the manager they will be listed like normal.

**Comment by blisstechllc** [comment]
Oh nice! That thought did cross my mind after I submitted this but I had to run out. That is perfect! Great work with this package!
