### ISSUE TITLE
[Feature] support the new flysystem v3

### ISSUE THREAD

**Issue by ctf0** [ctf0/Laravel-Media-Manager#159]
<s>https://flysystem.thephpleague.com/v2/docs/what-is-new/</s>
https://flysystem.thephpleague.com/docs/upgrade-from-1.x/

**Comment by jasperf** [comment]
We did experiment with storing images directly on DigitalOcean Spaces using `composer require league/flysystem-aws-s3-v3` . We had rate limiting issues however using Spaces. Each image is stored in 5 versions and on each media modal load all images would be displayed with thumbnails. Many , many requests all the time. Did read you mentioned https://github.com/thephpleague/flysystem-cached-adapter in another thread and that may help limiting the requests for the stored images. We did not experiment with that yet.  Looking forward to reading on this enhancement and willing to help out with testing for sure.

**Comment by ctf0** [comment]
> that may help limiting the requests for the stored images. We did not experiment with that yet

highly recommended to use the cache-adapter

> Looking forward to reading on this enhancement and willing to help out with testing for sure

probably not b4 next version of laravel v9 https://packagist.org/packages/laravel/framework#dev-master

**Comment by jasperf** [comment]
Understood the new Flysytem[[1]](https://blog.frankdejonge.nl/a-new-major-version-of-flysystem/)[[2]](https://flysystem.thephpleague.com/v2/docs/what-is-new/) has a lot of new advantages:

- Deterministic filesystem operations - In addition to a more streamlined API, each write call is now less expensive. Since writes now overwrite, there is no longer a file existence needed. For all the “over the network filesystems”, this is a big win! From 3-1 calls
- In V1, looking up mime-types could give performance penalties. In V2, this components was extracted into its own package called league/mime-type-detection.
- Developer experience was top of mind when creating V2 of Flysystem. Well-known issues were tackled. One of these was the response for a `listContents` call.
- errors are represented as exceptions. Every filesystem operation has a corresponding exception class. Each exception class explains what the originating operation was and what went wrong.

which would also make cloud storage work better without hitting 503s. Also understood that cached adapter will no longer be supported [[3]](https://github.com/laravel/framework/pull/33612). Perhaps because of all these new enhancements.

Still looking into delayed jobs, throttling and exponential back-offs [[4]](http://snags88.github.io/backoff-strategy-for-laravel-jobs), but I do feel like Flysystem 2 is going to help out a lot. I see it has been merged[[5]](https://github.com/laravel/framework/commit/609516125647e980136e4407042460b1ecf527f3) into Laravel Master already. The release is however not until September 2021 so we may try out Flysystem 2 sooner than that. Still debating this. But looking at the Laravel Master branch file changes needed we may have to wait.
