### ISSUE TITLE
[Question] Multilanguage Support

### ISSUE THREAD

**Issue by wei-jinn** [ctf0/Laravel-Media-Manager#166]
Greetings cft0. I noticed that the interface are translatable and I found them in lang > en > messages. However, some buttons in editor interface do not have their translations, for example: the button group of "brightness, contrast, saturation..." and "Clarity, 
 Vintage, Love...". May I know where to locate them to further carrying out translation?

Secondly, the folder name and file would be a set of string started with "5f8d..." as when I attempted create a new folder with other languages, for example Chinese words. When I tried to rename any file and folder, it would become empty and inaccessible. Do you have any suggestion on handling this?

![editor-button-translations](https://user-images.githubusercontent.com/45649909/96552898-fceb7700-12e6-11eb-8307-716e21156320.png)

![Invalid Naming](https://user-images.githubusercontent.com/45649909/96552949-0b399300-12e7-11eb-8ede-50c991488b48.png)

**Comment by ctf0** [comment]
> for example: the button group of "brightness, contrast, saturation..." and "Clarity,
Vintage, Love...". May I know where to locate them to further carrying out translation?

thanx for the heads up, they are added in the latest commit.
btw if you can send me a PR with translation for `Chinese` or any other language you will use for the manager, that would be awesome 🏆 

> When I tried to rename any file and folder, it would become empty and inaccessible

thats because of [the regex](https://github.com/ctf0/Laravel-Media-Manager/blob/39bbc9cb90557f46aa8e18c45069e80b8c5a0de9/src/App/Controllers/Modules/Utils.php#L55-L58)
and to get around it i would recommend overriding the method through using a new controller [wiki](https://github.com/ctf0/Laravel-Media-Manager/wiki/Have-More-Control-On-Uploads)
