### ISSUE TITLE
Filestack integration

### ISSUE THREAD

**Issue by meyer59** [ctf0/Laravel-Media-Manager#84]
> What version of Laravel are you using? (nothing lower than v5.4).

5.7

> is it an issue related to installation or usage ?

No

Hi
First, thanks for the great work.
Second, do you have any advice/tip about the best place in code/file to integrate the filestack api in the filemanager ? 
-I would like the drap & drop to upload directly to filestack 
-The upload button show the filestack modal
They have a great api. I am just asking for the best place in the manager to do that (Js side/ php side)
Thanks

**Comment by ctf0** [comment]
thanx for the idea, so far i have exactly that on my todo list ["where u can directly upload to the storage server"](https://github.com/ctf0/Laravel-Media-Manager/issues/11) instead of first uploading to ur app server but i haven't found any time to do that yet.

i cant say what exactly is needed in order to get it work but mostly it will be on the js side

**Comment by meyer59** [comment]
Thanks for the answer, hope you'll find time ;)
